<?php
require __DIR__ . '/../vendor/autoload.php';
$app = require_once __DIR__ . '/../bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Question;
use App\Models\PsbRegistration;

// 1. DATA SOAL KHUSUS MTs (15 Butir Soal)
$soalMts = [
    [
        'jenjang' => 'MTs',
        'kategori' => 'Matematika',
        'soal' => 'Hasil dari operasi hitung campuran bilangan bulat berikut adalah:\n$$(-12) + 25 \\times (-4) : 5 = \\dots$$',
        'opsi_a' => '-32',
        'opsi_b' => '-24',
        'opsi_c' => '-16',
        'opsi_d' => '8',
        'opsi_e' => '12',
        'kunci_jawaban' => 'A',
        'bobot' => 1,
        'pembahasan' => 'Dahulukan perkalian dan pembagian: 25 x (-4) = -100, -100 : 5 = -20, lalu (-12) + (-20) = -32.',
        'is_math' => true,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MTs',
        'kategori' => 'Matematika',
        'soal' => 'Bentuk sederhana dari pecahan aljabar berikut untuk $x \\neq \\pm 3$ adalah:\n$$\\frac{2x^2 + 5x - 3}{x^2 - 9}$$',
        'opsi_a' => '$\\frac{2x - 1}{x - 3}$',
        'opsi_b' => '$\\frac{2x + 1}{x + 3}$',
        'opsi_c' => '$\\frac{2x - 1}{x + 3}$',
        'opsi_d' => '$\\frac{x - 1}{x - 3}$',
        'opsi_e' => '$\\frac{2x + 3}{x - 3}$',
        'kunci_jawaban' => 'A',
        'bobot' => 1,
        'pembahasan' => 'Faktorisasi pembilang: (2x - 1)(x + 3), penyebut: (x - 3)(x + 3). Sederhanakan dengan membagi (x + 3), hasil akhir (2x - 1)/(x - 3).',
        'is_math' => true,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MTs',
        'kategori' => 'Matematika',
        'soal' => 'Sebuah denah gedung pondok pesantren berskala $1 : 250$. Jika panjang gedung asrama pada denah adalah $16\\text{ cm}$, maka panjang gedung sebenarnya adalah...',
        'opsi_a' => '30 meter',
        'opsi_b' => '40 meter',
        'opsi_c' => '50 meter',
        'opsi_d' => '60 meter',
        'opsi_e' => '80 meter',
        'kunci_jawaban' => 'B',
        'bobot' => 1,
        'pembahasan' => 'Jarak sebenarnya = 16 cm x 250 = 4.000 cm = 40 meter.',
        'is_math' => true,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MTs',
        'kategori' => 'IPA',
        'soal' => 'Perhatikan beberapa peristiwa perubahan materi berikut:\n1. Es mencair menjadi air\n2. Besi pagar berkarat\n3. Kayu dibakar menjadi arang\n4. Gula larut dalam air panas\nPeristiwa yang termasuk perubahan kimia adalah nomor...',
        'opsi_a' => '1 dan 4',
        'opsi_b' => '2 dan 3',
        'opsi_c' => '1 dan 3',
        'opsi_d' => '2 dan 4',
        'opsi_e' => '3 dan 4',
        'kunci_jawaban' => 'B',
        'bobot' => 1,
        'pembahasan' => 'Perubahan kimia menghasilkan zat baru dengan susunan kimia berbeda (perkaratan besi dan pembakaran kayu).',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MTs',
        'kategori' => 'IPA',
        'soal' => 'Organel sel yang berfungsi sebagai tempat berlangsungnya respirasi seluler dan menghasilkan energi dalam bentuk ATP adalah...',
        'opsi_a' => 'Ribosom',
        'opsi_b' => 'Mitokondria',
        'opsi_c' => 'Kloroplas',
        'opsi_d' => 'Badan Golgi',
        'opsi_e' => 'Lisosom',
        'kunci_jawaban' => 'B',
        'bobot' => 1,
        'pembahasan' => 'Mitokondria merupakan penghasil energi sel melalui proses respirasi aerob.',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MTs',
        'kategori' => 'Bahasa Arab',
        'soal' => 'مَا مَعْنَى الْجُمْلَةِ التَّالِيَةِ:\n"يَذْهَبُ التِّلْمِيْذُ إِلَى الْمَدْرَسَةِ فِي السَّاعَةِ السَّادِسَةِ صَبَاحًا"',
        'opsi_a' => 'Guru itu pergi ke madrasah pada jam enam pagi',
        'opsi_b' => 'Murid itu pergi ke madrasah pada jam enam pagi',
        'opsi_c' => 'Murid itu pulang dari madrasah pada jam enam sore',
        'opsi_d' => 'Santri itu tidur di asrama pada jam enam pagi',
        'opsi_e' => 'Pegawai itu pergi ke kantor pada jam enam pagi',
        'kunci_jawaban' => 'B',
        'bobot' => 1,
        'pembahasan' => '"التِّلْمِيْذُ" = murid, "يَذْهَبُ" = pergi, "السَّادِسَةِ صَبَاحًا" = jam enam pagi.',
        'is_math' => false,
        'is_arabic' => true,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MTs',
        'kategori' => 'Bahasa Arab',
        'soal' => 'فِي جُمْلَةِ: "قَرَأَ أَحْمَدُ الْقُرْآنَ"، كَلِمَةُ "الْقُرْآنَ" تُعْرَبُ...',
        'opsi_a' => 'فَاعِلٌ مَرْفُوْعٌ',
        'opsi_b' => 'مَفْعُوْلٌ بِهِ مَنْصُوْبٌ',
        'opsi_c' => 'مُبْتَدَأٌ مَرْفُوْعٌ',
        'opsi_d' => 'خَبَرٌ مَرْفُوْعٌ',
        'opsi_e' => 'مَجْرُوْرٌ بِالْكَسْرَةِ',
        'kunci_jawaban' => 'B',
        'bobot' => 1,
        'pembahasan' => 'Kata Al-Qur\'an berkedudukan sebagai objek (Maf\'ul bih) yang dinashobkan dengan fathah.',
        'is_math' => false,
        'is_arabic' => true,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MTs',
        'kategori' => 'Pendidikan Agama Islam',
        'soal' => 'Shalat sunnah yang dikerjakan secara berjamaah pada malam hari di bulan suci Ramadhan sesudah shalat Isya disebut shalat...',
        'opsi_a' => 'Witir',
        'opsi_b' => 'Tahajjud',
        'opsi_c' => 'Tarawih',
        'opsi_d' => 'Istikharah',
        'opsi_e' => 'Dhuha',
        'kunci_jawaban' => 'C',
        'bobot' => 1,
        'pembahasan' => 'Shalat Tarawih adalah shalat sunnah muakkad khusus di malam bulan suci Ramadhan.',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MTs',
        'kategori' => 'Tajwid & Al-Qur\'an',
        'soal' => 'Hukum bacaan nun sukun bertemu huruf ب (Ba) pada lafadz مَنْ بَعْدِ dinamakan hukum bacaan...',
        'opsi_a' => 'Idzhar Halqi',
        'opsi_b' => 'Idgham Bighunnah',
        'opsi_c' => 'Iqlab',
        'opsi_d' => 'Ikhfa Haqiqi',
        'opsi_e' => 'Idgham Bilaghunnah',
        'kunci_jawaban' => 'C',
        'bobot' => 1,
        'pembahasan' => 'Iqlab adalah hukum nun sukun atau tanwin bertemu huruf Ba (ب), dibaca berubah menjadi suara mim disertai dengung.',
        'is_math' => false,
        'is_arabic' => true,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MTs',
        'kategori' => 'Bahasa Indonesia',
        'soal' => 'Bacalah kutipan berikut:\n"Pondok Pesantren Hidayatullah memiliki lingkungan yang asri dan bersih. Pepohonan rindang tumbuh subur di sepanjang jalan asrama santri."\nGagasan pokok paragraf tersebut adalah...',
        'opsi_a' => 'Kebersihan dan keasrian lingkungan pondok pesantren',
        'opsi_b' => 'Jenis tanaman di sekitar asrama santri',
        'opsi_c' => 'Aktivitas santri di pagi hari',
        'opsi_d' => 'Luas wilayah pondok pesantren',
        'opsi_e' => 'Kerindangan pepohonan di pinggir jalan',
        'kunci_jawaban' => 'A',
        'bobot' => 1,
        'pembahasan' => 'Gagasan utama terletak pada kalimat deduktif di awal paragraf mengenai kebersihan dan keasrian pondok.',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MTs',
        'kategori' => 'Bahasa Inggris',
        'soal' => 'Ahmad: "Where are you going, Farhan?"\nFarhan: "I am going to the ... to borrow an Islamic history book."',
        'opsi_a' => 'Canteen',
        'opsi_b' => 'Library',
        'opsi_c' => 'Dormitory',
        'opsi_d' => 'Mosque',
        'opsi_e' => 'Laboratory',
        'kunci_jawaban' => 'B',
        'bobot' => 1,
        'pembahasan' => 'Library (perpustakaan) adalah tempat untuk meminjam buku.',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MTs',
        'kategori' => 'Kepesantrenan',
        'soal' => 'Sikap tawadhu\' seorang santri kepada kiai dan para asatidz dalam kehidupan pesantren tercermin pada perilaku...',
        'opsi_a' => 'Berbicara lantang di depan para guru',
        'opsi_b' => 'Mendengarkan nasehat guru dengan sopan dan rendah hati',
        'opsi_c' => 'Menolak tugas piket kebersihan asrama',
        'opsi_d' => 'Tidak menghiraukan tata tertib asrama',
        'opsi_e' => 'Membanggakan kehebatan diri sendiri',
        'kunci_jawaban' => 'B',
        'bobot' => 1,
        'pembahasan' => 'Tawadhu\' berarti rendah hati dan menghormati guru dengan penuh adab.',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MTs',
        'kategori' => 'IPA',
        'soal' => 'Sebuah sepeda motor bergerak dengan kecepatan tetap $15\\text{ m/s}$. Jarak yang ditempuh sepeda motor tersebut selama $20\\text{ detik}$ adalah...',
        'opsi_a' => '150 meter',
        'opsi_b' => '200 meter',
        'opsi_c' => '300 meter',
        'opsi_d' => '350 meter',
        'opsi_e' => '450 meter',
        'kunci_jawaban' => 'C',
        'bobot' => 1,
        'pembahasan' => 's = v x t = 15 m/s x 20 s = 300 meter.',
        'is_math' => true,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MTs',
        'kategori' => 'Pendidikan Agama Islam',
        'soal' => 'Rukun wudhu yang keempat setelah membasuh kedua tangan sampai ke siku adalah...',
        'opsi_a' => 'Membasuh muka',
        'opsi_b' => 'Mengusap sebagian kepala',
        'opsi_c' => 'Membasuh kedua telinga',
        'opsi_d' => 'Membasuh kedua kaki hingga mata kaki',
        'opsi_e' => 'Berkumur-kumur',
        'kunci_jawaban' => 'B',
        'bobot' => 1,
        'pembahasan' => 'Urutan rukun wudhu: 1. Niat, 2. Membasuh wajah, 3. Membasuh kedua tangan hingga siku, 4. Mengusap sebagian kepala, 5. Membasuh kedua kaki, 6. Tertib.',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MTs',
        'kategori' => 'Bahasa Indonesia',
        'soal' => 'Penulisan kelompok kata baku yang tepat menurut Pedoman Umum Ejaan Bahasa Indonesia (PUEBI) adalah...',
        'opsi_a' => 'Praktek, ijin, resiko',
        'opsi_b' => 'Praktik, izin, risiko',
        'opsi_c' => 'Praktik, ijin, resiko',
        'opsi_d' => 'Praktek, izin, resiko',
        'opsi_e' => 'Praktik, izin, rilis',
        'kunci_jawaban' => 'B',
        'bobot' => 1,
        'pembahasan' => 'Bentuk baku yang benar adalah praktik, izin, dan risiko.',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ]
];

// 2. DATA SOAL KHUSUS MA (15 Butir Soal)
$soalMa = [
    [
        'jenjang' => 'MA',
        'kategori' => 'Matematika',
        'soal' => 'Dengan menggunakan rumus sudut ganda dan penjumlahan sinus, nilai eksak dari fungsi trigonometri berikut adalah:\n$$\\sin 75^\\circ = \\dots$$',
        'opsi_a' => '$\\frac{\\sqrt{6} + \\sqrt{2}}{4}$',
        'opsi_b' => '$\\frac{\\sqrt{6} - \\sqrt{2}}{4}$',
        'opsi_c' => '$\\frac{\\sqrt{3} + 1}{2}$',
        'opsi_d' => '$\\frac{\\sqrt{2} + 1}{4}$',
        'opsi_e' => '$\\frac{\\sqrt{6} + \\sqrt{3}}{4}$',
        'kunci_jawaban' => 'A',
        'bobot' => 1,
        'pembahasan' => 'sin(45 + 30) = sin 45 cos 30 + cos 45 sin 30 = (√2/2)(√3/2) + (√2/2)(1/2) = (√6 + √2)/4.',
        'is_math' => true,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MA',
        'kategori' => 'Matematika',
        'soal' => 'Diketahui fungsi aljabar polinomial $f(x) = 3x^3 - 5x^2 + 7x - 12$. Nilai turunan pertama fungsi tersebut pada $x = 2$ atau $f\'(2)$ adalah...',
        'opsi_a' => '19',
        'opsi_b' => '21',
        'opsi_c' => '23',
        'opsi_d' => '27',
        'opsi_e' => '31',
        'kunci_jawaban' => 'C',
        'bobot' => 1,
        'pembahasan' => 'f\'(x) = 9x^2 - 10x + 7. Untuk x = 2: f\'(2) = 9(4) - 10(2) + 7 = 36 - 20 + 7 = 23.',
        'is_math' => true,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MA',
        'kategori' => 'Matematika',
        'soal' => 'Jumlah tak hingga dari deret geometri konvergen berikut adalah:\n$$S_\\infty = 18 + 12 + 8 + \\frac{16}{3} + \\dots$$',
        'opsi_a' => '36',
        'opsi_b' => '48',
        'opsi_c' => '54',
        'opsi_d' => '60',
        'opsi_e' => '72',
        'kunci_jawaban' => 'C',
        'bobot' => 1,
        'pembahasan' => 'Suku pertama a = 18, rasio r = 12/18 = 2/3. Jumlah tak hingga S = a / (1 - r) = 18 / (1 - 2/3) = 18 / (1/3) = 54.',
        'is_math' => true,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MA',
        'kategori' => 'Bahasa Arab',
        'soal' => 'فِي قَوْلِهِ تَعَالَى: "إِنَّ الْمُتَّقِيْنَ فِي جَنَّاتٍ وَنَهَرٍ"، حُكْمُ إِعْرَابِ كَلِمَةِ "الْمُتَّقِيْنَ" هُوَ...',
        'opsi_a' => 'اسْمُ إِنَّ مَنْصُوْبٌ بِالْيَاءِ لِأَنَّهُ جَمْعُ مُذَكَّرٍ سَالِمٌ',
        'opsi_b' => 'خَبَرُ إِنَّ مَرْفُوْعٌ بِالْوَاوِ',
        'opsi_c' => 'فَاعِلٌ مَرْفُوْعٌ بِالضَّمَّةِ',
        'opsi_d' => 'مَفْعُوْلٌ بِهِ مَجْرُوْرٌ بِالْكَسْرَةِ',
        'opsi_e' => 'اسْمُ إِنَّ مَرْفُوْعٌ بِالْأَلِفِ',
        'kunci_jawaban' => 'A',
        'bobot' => 1,
        'pembahasan' => 'Isim Inna dinashobkan dengan tanda Ya karena jamak mudzakkar salim.',
        'is_math' => false,
        'is_arabic' => true,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MA',
        'kategori' => 'Bahasa Arab',
        'soal' => 'قَالَ تَعَالَى: "وَاشْتَعَلَ الرَّأْسُ شَيْبًا". هَذَا التَّعْبِيْرُ الْبَلَاغِيُّ يَتَضَمَّنُ نَوْعًا مِنَ...',
        'opsi_a' => 'الِاسْتِعَارَةِ الْمَكْنِيَّةِ',
        'opsi_b' => 'التَّشْبِيْهِ الْبَلِيْغِ',
        'opsi_c' => 'الْجِنَاسِ التَّامِّ',
        'opsi_d' => 'الطِّبَاقِ الْمُوجَبِ',
        'opsi_e' => 'السَّجْعِ',
        'kunci_jawaban' => 'A',
        'bobot' => 1,
        'pembahasan' => 'Menyerupakan meratanya uban putih di kepala dengan jilatan api yang menyala (Isti\'arah Makniyyah).',
        'is_math' => false,
        'is_arabic' => true,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MA',
        'kategori' => 'Pendidikan Agama Islam',
        'soal' => 'Kaidah Ushul Fiqih yang berbunyi:\n"الأَصْلُ فِي الأَشْيَاءِ الإِبَاحَةُ حَتَّى يَدُلَّ الدَّلِيلُ عَلَى التَّحْرِيمِ"\nmemiliki arti dasar...',
        'opsi_a' => 'Hukum asal segala sesuatu (muamalah) adalah mubah/boleh sampai ada dalil yang mengharamkannya',
        'opsi_b' => 'Segala bentuk peribadahan boleh dilakukan tanpa perlu tuntunan dalil',
        'opsi_c' => 'Keragu-raguan dapat menggugurkan keyakinan yang telah pasti',
        'opsi_d' => 'Kesulitan pasti mendatangkan kemudahan hukum syariat',
        'opsi_e' => 'Kemudharatan harus dihilangkan dengan segala cara',
        'kunci_jawaban' => 'A',
        'bobot' => 1,
        'pembahasan' => 'Kaidah ini merupakan landasan fiqih muamalah bahwa segala urusan duniawi asalnya halal sampai ada dalil larangan.',
        'is_math' => false,
        'is_arabic' => true,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MA',
        'kategori' => 'Bahasa Inggris',
        'soal' => 'If the students had studied seriously before the entrance examination, they ... the highest score in their class.',
        'opsi_a' => 'will achieve',
        'opsi_b' => 'would achieve',
        'opsi_c' => 'would have achieved',
        'opsi_d' => 'had achieved',
        'opsi_e' => 'have achieved',
        'kunci_jawaban' => 'C',
        'bobot' => 1,
        'pembahasan' => 'Conditional sentence Type 3: If + Past Perfect, Subject + would have + Verb 3.',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MA',
        'kategori' => 'Bahasa Inggris',
        'soal' => 'The valuable Islamic historical manuscripts in the pesantren library ... by prominent Muslim scholars centuries ago.',
        'opsi_a' => 'is written',
        'opsi_b' => 'was written',
        'opsi_c' => 'were written',
        'opsi_d' => 'have written',
        'opsi_e' => 'wrote',
        'kunci_jawaban' => 'C',
        'bobot' => 1,
        'pembahasan' => 'Subjek jamak (manuscripts) dalam bentuk kalimat pasif lampau (Past Simple Passive) menggunakan were written.',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MA',
        'kategori' => 'IPA',
        'soal' => 'Pada proses sintesis protein seluler, peristiwa transkripsi rantai kode genetik DNA menjadi untai mRNA berlangsung di dalam...',
        'opsi_a' => 'Sitoplasma',
        'opsi_b' => 'Nukleus (Inti Sel)',
        'opsi_c' => 'Retikulum Endoplasma Kasar',
        'opsi_d' => 'Vakuola',
        'opsi_e' => 'Sentriol',
        'kunci_jawaban' => 'B',
        'bobot' => 1,
        'pembahasan' => 'Transkripsi DNA ke mRNA berlangsung di dalam inti sel (nukleus), sebelum ditranslasi di ribosom.',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MA',
        'kategori' => 'IPA',
        'soal' => 'Sebuah gelombang memiliki frekuensi $50\\text{ Hz}$ dan panjang gelombang $\\lambda = 6\\text{ meter}$. Nilai cepat rambat gelombang tersebut adalah...',
        'opsi_a' => '150 m/s',
        'opsi_b' => '200 m/s',
        'opsi_c' => '250 m/s',
        'opsi_d' => '300 m/s',
        'opsi_e' => '350 m/s',
        'kunci_jawaban' => 'D',
        'bobot' => 1,
        'pembahasan' => 'Cepat rambat gelombang v = λ x f = 6 m x 50 Hz = 300 m/s.',
        'is_math' => true,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MA',
        'kategori' => 'Bahasa Indonesia',
        'soal' => 'Kalimat berikut ini yang menggunakan majas antitesis secara tepat adalah...',
        'opsi_a' => 'Wajahnya berseri laksana rembulan di malam purnama',
        'opsi_b' => 'Tua muda, kaya miskin, semuanya berkedudukan sama di hadapan hukum Allah SWT',
        'opsi_c' => 'Angin malam berbisik lembut menyapa para santri',
        'opsi_d' => 'Pena ini menjadi saksi bisu perjuangan para ulama nusantara',
        'opsi_e' => 'Suaranya menggelegar membelah keheningan asrama',
        'kunci_jawaban' => 'B',
        'bobot' => 1,
        'pembahasan' => 'Majas antitesis menggunakan paduan kata yang saling berlawanan arti (tua-muda, kaya-miskin).',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MA',
        'kategori' => 'Tajwid & Al-Qur\'an',
        'soal' => 'Surah-surah Al-Qur\'an yang diturunkan oleh Allah SWT sebelum peristiwa hijrah Rasulullah SAW ke Madinah secara terminologi Ulumul Qur\'an dinamakan surah...',
        'opsi_a' => 'Madaniyyah',
        'opsi_b' => 'Makkiyyah',
        'opsi_c' => 'Mu\'allaqah',
        'opsi_d' => 'Mansukhah',
        'opsi_e' => 'Muthlaqah',
        'kunci_jawaban' => 'B',
        'bobot' => 1,
        'pembahasan' => 'Menurut mayoritas ulama tafsir, surah Makkiyyah adalah yang diturunkan sebelum hijrah Nabi SAW.',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MA',
        'kategori' => 'Kepesantrenan',
        'soal' => 'Kitab kuning klasik rujukan etika santri dalam menuntut ilmu karya Imam Az-Zarnuji yang sangat masyhur dipelajari di pesantren adalah...',
        'opsi_a' => 'Bidayatul Hidayah',
        'opsi_b' => 'Ta\'limul Muta\'allim',
        'opsi_c' => 'Riyadhus Shalihin',
        'opsi_d' => 'Fathul Qorib',
        'opsi_e' => 'Al-Hikam',
        'kunci_jawaban' => 'B',
        'bobot' => 1,
        'pembahasan' => 'Ta\'limul Muta\'allim karya Syekh Burhanuddin Az-Zarnuji berisi panduan adab dan metode belajar santri.',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MA',
        'kategori' => 'Pendidikan Agama Islam',
        'soal' => 'Hadits yang sanadnya bersambung, diriwayatkan oleh perawi yang adil, dhabith (kuat hafalannya), tidak ada syadz, dan terbebas dari \'illat dinamakan hadits...',
        'opsi_a' => 'Shahih',
        'opsi_b' => 'Hasan',
        'opsi_c' => 'Dha\'if',
        'opsi_d' => 'Maudhu\'',
        'opsi_e' => 'Mu\'allaq',
        'kunci_jawaban' => 'A',
        'bobot' => 1,
        'pembahasan' => 'Lima syarat hadits Shahih: bersambung sanad, rawi adil, rawi dhabith, selamat dari syadz dan selamat dari cacat (\'illat).',
        'is_math' => false,
        'is_arabic' => false,
        'is_active' => true,
    ],
    [
        'jenjang' => 'MA',
        'kategori' => 'Bahasa Arab',
        'soal' => 'تَرْجِمِ الْجُمْلَةَ التَّالِيَةَ إِلَى اللُّغَةِ الإِنْدُوْنِيْسِيَّةِ:\n"تَسْعَى الْمَعَاهِدُ الإِسْلامِيَّةُ إِلَى إِعْدَادِ جِيْلٍ قُرْآنِيٍّ مُتَمَسِّكٍ بِالأَخْلاقِ الْفَاضِلَةِ"',
        'opsi_a' => 'Pondok pesantren berupaya menyiapkan generasi Qur\'ani yang berpegang teguh pada akhlak mulia',
        'opsi_b' => 'Guru-guru madrasah mengajarkan Al-Qur\'an kepada generasi muda di masjid',
        'opsi_c' => 'Generasi Qur\'ani belajar di pesantren agar menjadi pemimpin bangsa masa depan',
        'opsi_d' => 'Pendidikan akhlak mulia wajib diajarkan kepada santri di pondok pesantren',
        'opsi_e' => 'Lembaga Islam mendirikan asrama untuk para santri penghafal Al-Qur\'an',
        'kunci_jawaban' => 'A',
        'bobot' => 1,
        'pembahasan' => '"تَسْعَى" = berupaya, "إِعْدَادِ جِيْلٍ قُرْآنِيٍّ" = menyiapkan generasi Qur\'ani, "مُتَمَسِّكٍ بِالأَخْلاقِ الْفَاضِلَةِ" = berpegang teguh pada akhlak mulia.',
        'is_math' => false,
        'is_arabic' => true,
        'is_active' => true,
    ]
];

// Masukkan Soal MTs jika belum ada
$insertedMts = 0;
foreach ($soalMts as $item) {
    $exists = Question::where('soal', $item['soal'])->first();
    if (!$exists) {
        Question::create($item);
        $insertedMts++;
    }
}

// Masukkan Soal MA jika belum ada
$insertedMa = 0;
foreach ($soalMa as $item) {
    $exists = Question::where('soal', $item['soal'])->first();
    if (!$exists) {
        Question::create($item);
        $insertedMa++;
    }
}

// Reset urutan soal acak di akun uji coba MTs dan MA agar saat login langsung mengocok dan mengambil soal baru
PsbRegistration::where('jenjang', 'like', '%MTs%')->update(['cbt_soal_urutan_json' => null]);
PsbRegistration::where('jenjang', 'like', '%MA%')->update(['cbt_soal_urutan_json' => null]);

echo "BERHASIL!\n";
echo "- $insertedMts butir soal khusus MTs telah ditambahkan ke database.\n";
echo "- $insertedMa butir soal khusus MA telah ditambahkan ke database.\n";
echo "Total soal MTs sekarang: " . Question::where('jenjang', 'MTs')->count() . "\n";
echo "Total soal MA sekarang: " . Question::where('jenjang', 'MA')->count() . "\n";
echo "Total soal Semua sekarang: " . Question::where('jenjang', 'Semua')->count() . "\n";
echo "Total keseluruhan soal: " . Question::count() . "\n";
